Added support for sftp client posix rename
apache/mina-sshd pull request #180
Opened 2021-01-13 10:31 UTC by chrjoedal

The read-me file for SFTP states, that posix-rename is supported, but the posix rename extension for the sftp client was newer made.
I have made the small implementation, supporting the posix-rename command for the sftp client.

2021-01-13 12:10 UTC, gnodet commented
@chrjoedal looks good. Is there any way you could add a test for the new extension ?

2021-01-13 13:13 UTC, chrjoedal commented
> @chrjoedal looks good. Is there any way you could add a test for the new extension ?

I have tried to give it a look.
Problem is, that I have only created the client-side support of posix-rename
I have not looked into enabling the support for posix-rename server-side.
When I then try to make the unit-test for posix-rename, I get the exception:
`java.lang.AssertionError: Extension not supported: posix-rename@openssh.com`
It is therefore a bit hard to test, but I am open for suggestions, as this is my first code change to mina-sshd, so there are many elements in the code, I have not covered.

I have made the test with my local sftp server (for which I needed the feature), where it works fine.

2021-01-13 13:45 UTC, gnodet commented
> > @chrjoedal looks good. Is there any way you could add a test for the new extension ?
> 
> I have tried to give it a look.
> Problem is, that I have only created the client-side support of posix-rename
> I have not looked into enabling the support for posix-rename server-side.
> When I then try to make the unit-test for posix-rename, I get the exception:
> `java.lang.AssertionError: Extension not supported: posix-rename@openssh.com`
> It is therefore a bit hard to test, but I am open for suggestions, as this is my first code change to mina-sshd, so there are many elements in the code, I have not covered.
> 
> I have made the test with my local sftp server (for which I needed the feature), where it works fine.

Ah, the best way would be to add the server-side too.  I don't think it is much more complicated than the server side, the only thing is that we'll need to actual _rename_ implementation, but that should not be very difficult.  Let me know if you need some help.

2021-01-13 14:12 UTC, chrjoedal commented
> > > @chrjoedal looks good. Is there any way you could add a test for the new extension ?
> > 
> > 
> > I have tried to give it a look.
> > Problem is, that I have only created the client-side support of posix-rename
> > I have not looked into enabling the support for posix-rename server-side.
> > When I then try to make the unit-test for posix-rename, I get the exception:
> > `java.lang.AssertionError: Extension not supported: posix-rename@openssh.com`
> > It is therefore a bit hard to test, but I am open for suggestions, as this is my first code change to mina-sshd, so there are many elements in the code, I have not covered.
> > I have made the test with my local sftp server (for which I needed the feature), where it works fine.
> 
> Ah, the best way would be to add the server-side too. I don't think it is much more complicated than the server side, the only thing is that we'll need to actual _rename_ implementation, but that should not be very difficult. Let me know if you need some help.

I have never used the server part of this module - only the client path. So I do not think I am the right for the job, as I have newer used it, started it, or even looked in the code.

I just made this little extension to the client, and submitted it, so others could benefit from it as well :)

2021-01-13 17:00 UTC, lgoldstein requested changes

2021-01-13 17:02 UTC, lgoldstein commented
>> Ah, the best way would be to add the server-side too.

I agree that it would be best, but the PR has value without it as well. @gnodet Unless there is a strong objection I am willing to merge this PR once the minor fix I pointed out is done.

2021-01-13 17:04 UTC, gnodet commented
> > > Ah, the best way would be to add the server-side too.
> 
> I agree that it would be best, but the PR has value without it as well. @gnodet Unless there is a strong objection I am willing to merge this PR once the minor fix I pointed out is done.

Agreed, no problem to merge the client side.

2021-01-14 07:05 UTC, chrjoedal commented on sshd-sftp/src/main/java/org/apache/sshd/sftp/client/extensions/openssh/helpers/OpenSSHPosixRenameExtensionImpl.java
> +        Buffer buffer = getCommandBuffer(Integer.BYTES + ((CharSequence) oldPath).length() + ((CharSequence) newPath).length());
You are correct - I have made a push, fixing it.
It was a copy-paste error from an other place in the code.

2021-01-14 07:10 UTC, chrjoedal commented
I made the minor fix suggested, and have made a new push.

2021-01-14 16:54 UTC, lgoldstein commented
Merged + acknowledgement as [498bf10e58d47d2899fe42c3dda4074b2ec63ca8](https://github.com/apache/mina-sshd/commit/498bf10e58d47d2899fe42c3dda4074b2ec63ca8) - many thanks for the contribution. You can close the PR.

2021-01-15 08:03 UTC, closed without merging